{{- if .Values.services.overseerr.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: overseerr
  namespace: default
  labels:
    app.kubernetes.io/name: overseerr
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.services.overseerr.ports.http }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: overseerr
{{- end }}
