{{- if .Values.services.autobrr.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: autobrr
  namespace: default
  labels:
    app.kubernetes.io/name: autobrr
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.services.autobrr.ports.http }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: autobrr
{{- end}}