{{- if .Values.services.thelounge.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: thelounge
  namespace: default
  labels:
    app.kubernetes.io/name: thelounge
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.services.thelounge.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: thelounge
{{- end }}
