apiVersion: apps/v1
kind: Deployment
metadata:
  name: huginn
  namespace: default
  labels:
    app.kubernetes.io/name: huginn
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: huginn
  template:
    metadata:
      labels:
        app.kubernetes.io/name: huginn
    spec:
      containers:
        - name: huginn
          image: "{{ .Values.services.huginn.image.repository }}:{{ .Values.services.huginn.image.tag }}"
          imagePullPolicy: {{ .Values.services.huginn.image.pullPolicy }}
          env:
            - name: TZ
              value: "{{ .Values.common.tz }}"
            - name: INVITATION_CODE
              value: "{{ .Values.services.huginn.invitation_code }}"
            - name: APP_SECRET_TOKEN
              value: "{{ .Values.services.huginn.app_secret_token }}"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: huginn-data
              mountPath: /var/lib/mysql
      volumes:
        - name: huginn-data
          hostPath:
            path: "{{ .Values.services.huginn.data }}"
            type: Directory
