{{- if .Values.services.gotify.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotify
  namespace: default
  labels:
    app.kubernetes.io/name: gotify
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.services.gotify.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: gotify
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gotify
    spec:
      containers:
        - name: gotify
          image: "{{ .Values.services.gotify.image.repository }}:{{ .Values.services.gotify.image.tag }}"
          imagePullPolicy: {{ .Values.services.gotify.image.pullPolicy }}
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "{{ .Values.common.tz }}"
          ports:
            - name: http
              containerPort: {{ .Values.services.gotify.ports.http }}
              protocol: TCP
          volumeMounts:
            - name: gotify-data
              mountPath: /app/data

      volumes:
        - name: gotify-data
          hostPath:
            path: "{{ .Values.services.gotify.data }}"
            type: Directory
{{- end }}