{{- if .Values.services.gotify.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: gotify
  namespace: default
  labels:
    app.kubernetes.io/name: gotify
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.services.gotify.ports.http }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: gotify
{{- end }}
