{{- if .Values.services.prowlarr.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: default
  labels:
    app.kubernetes.io/name: prowlarr
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.services.prowlarr.replicaCount }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: prowlarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prowlarr
    spec:
      containers:
        - name: prowlarr
          image: "{{ .Values.services.prowlarr.image.repository }}:{{ .Values.services.prowlarr.image.tag }}"
          imagePullPolicy: {{ .Values.services.prowlarr.image.pullPolicy }}
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "{{ .Values.common.tz }}"
          ports:
            - name: http
              containerPort: {{ .Values.services.prowlarr.ports.http }}
              protocol: TCP
          volumeMounts:
            - name: prowlarr-config
              mountPath: /config
            - name: downloads
              mountPath: /downloads

      volumes:
        - name: prowlarr-config
          hostPath:
            path: "{{ .Values.services.prowlarr.config }}"
            type: Directory
        - name: downloads
          hostPath:
            path: "{{ .Values.services.qbittorrent.downloads }}"
            type: Directory
{{- end }}