{{- if .Values.services.tautulli.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: tautulli
  namespace: default
  labels:
    app.kubernetes.io/name: tautulli
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.services.tautulli.ports.http }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: tautulli
{{- end }}
