{{- if .Values.services.playwright.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: playwright
  namespace: default
  labels:
    app.kubernetes.io/name: playwright
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.services.playwright.ports.http }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: playwright
{{- end }}