{{- if .Values.services.apprise.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: apprise
  namespace: default
  labels:
    app.kubernetes.io/name: apprise
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.services.apprise.ports.http }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: apprise
{{- end }}