
{{- if .Values.services.sabnzbd.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: sabnzbd
  namespace: default
  labels:
    app.kubernetes.io/name: sabnzbd
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.services.sabnzbd.ports.http }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: sabnzbd
{{- end }}
